language: c++
compiler:
  - gcc
  - clang
before_install:
  - sudo pip install cpp-coveralls==0.3.1
before_script:
  - cmake -DCOVERAGE=true .
script:
  - make && make test
after_success:
  - coveralls --include include --include src --gcov-options '\-lp'